name: Build FoundationDB.Client.Native Package

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the client to download'
        required: true
        default: 'latest'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - name: Install .NET SDK
      uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # v4.0.1
      with:
        dotnet-version: 9.0.x
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
    - name: Build (Release)
      run: dotnet build -c Release
    - name: Run download-and-verify.ps1
      run: |
        cd FoundationDB.Client.Native
        pwsh ./DownloadBinaries.ps1 `
          -version "${{ github.event.inputs.version }}" `
          -manifestPath "./manifest.json" `
          -outputDir "."
    - name: NuGet Pack
      env:
        DISABLE_NATIVE_PACKAGE: false
      run: dotnet pack ./FoundationDB.Client.Native/FoundationDB.Client.Native.csproj -c Release --output Redist
    - name: Upload artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: NuGet Packages
        path: |
          Redist/*.nupkg
          Redist/*.snupkg
        if-no-files-found: error
